insert into BANK (CODE, SWIFT, NAME, NAME_IN_ENGLISH, DISPLAY_ORDER, DELETED, DELETED_TIME, MODIFIED_TIME, CREATED_TIME)
values ('001',	'BOKRKRSE', '한국은행', 'Bank of Korea', 5, 0, null, current_timestamp, current_timestamp);

insert into BANK (CODE, SWIFT, NAME, NAME_IN_ENGLISH, DISPLAY_ORDER, DELETED, DELETED_TIME, MODIFIED_TIME, CREATED_TIME)
values ('002',	'KODBKRSE', '산업은행', 'Korea development bank', 4, 0, null, current_timestamp, current_timestamp);

insert into BANK (CODE, SWIFT, NAME, NAME_IN_ENGLISH, DISPLAY_ORDER, DELETED, DELETED_TIME, MODIFIED_TIME, CREATED_TIME)
values ('003',	'IBKOKRSE', '기업은행', 'Industrial Bank of Korea', 3, 0, null, current_timestamp, current_timestamp);

insert into BANK (CODE, SWIFT, NAME, NAME_IN_ENGLISH, DISPLAY_ORDER, DELETED, DELETED_TIME, MODIFIED_TIME, CREATED_TIME)
values ('004',	'CZNBKRSE', '국민은행', 'Kookmin bank', 2, 0, null, current_timestamp, current_timestamp);

insert into BANK (CODE, SWIFT, NAME, NAME_IN_ENGLISH, DISPLAY_ORDER, DELETED, DELETED_TIME, MODIFIED_TIME, CREATED_TIME)
values ('005',	'KOEXKRSE', '외환은행', 'Korea Exchange bank', 1, 0, null, current_timestamp, current_timestamp);

-- Indonesia FINNET Bank transfer
insert into MTO (CODE, COUNTRY, CURRENCY, REMITTANCE_OPTION, FEE_CURRENCY, FEE, EXCHANGE_SPREAD, EXPOSE, DELETED, MODIFIED_TIME, CREATED_TIME)
values ('FINNET', 'ID', 'IDR', 'BANK_TRANSFER', 'KRW', '4000', 0.985, TRUE, FALSE, current_timestamp, current_time);

insert into MTO_SERVICE_CENTER(MTO_ID, DISPLAY_ORDER, SERVICE_CENTER_CODE, LOCAL_CODE, DISPLAY_NAME, LOCAL_NAME, DELETED, MODIFIED_TIME, CREATED_TIME)
values ((select ID from MTO where CODE='FINNET' and COUNTRY='ID' and CURRENCY='IDR' and REMITTANCE_OPTION='BANK_TRANSFER'),
2, 'FNBT-002', '3', 'BANK EKSPOR INDONESIA', 'BANK EKSPOR INDONESIA', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

insert into MTO_SERVICE_CENTER(MTO_ID, DISPLAY_ORDER, SERVICE_CENTER_CODE, LOCAL_CODE, DISPLAY_NAME, LOCAL_NAME, DELETED, MODIFIED_TIME, CREATED_TIME)
values ((select ID from MTO where CODE='FINNET' and COUNTRY='ID' and CURRENCY='IDR' and REMITTANCE_OPTION='BANK_TRANSFER'),
1, 'FNBT-001', '2', 'BANK BRI', 'BANK BRI', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Indonesia FINNET Cash pickup
insert into MTO (CODE, COUNTRY, CURRENCY, REMITTANCE_OPTION, FEE_CURRENCY, FEE, EXCHANGE_SPREAD, EXPOSE, DELETED, MODIFIED_TIME, CREATED_TIME)
values ('FINNET', 'ID', 'IDR', 'CASH_PICK_UP', 'KRW', '8000', 0.975, TRUE, FALSE, current_timestamp, current_time);

insert into MTO_SERVICE_CENTER(MTO_ID, DISPLAY_ORDER, SERVICE_CENTER_CODE, LOCAL_CODE, DISPLAY_NAME, LOCAL_NAME, DELETED, MODIFIED_TIME, CREATED_TIME)
values ((select ID from MTO where CODE='FINNET' and COUNTRY='ID' and CURRENCY='IDR' and REMITTANCE_OPTION='CASH_PICK_UP'),
1, 'FNCP-001', null, 'Alfamart', 'Alfamart', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

insert into MTO_SERVICE_CENTER(MTO_ID, DISPLAY_ORDER, SERVICE_CENTER_CODE, LOCAL_CODE, DISPLAY_NAME, LOCAL_NAME, DELETED, MODIFIED_TIME, CREATED_TIME)
values ((select ID from MTO where CODE='FINNET' and COUNTRY='ID' and CURRENCY='IDR' and REMITTANCE_OPTION='CASH_PICK_UP'),
2, 'FNCP-002', null, 'BTN', 'BTN', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--Nepal EASYLINK Bank transfer
insert into MTO (CODE, COUNTRY, CURRENCY, REMITTANCE_OPTION, FEE_CURRENCY, FEE, EXCHANGE_SPREAD, EXPOSE, DELETED, MODIFIED_TIME, CREATED_TIME)
values ('EASYLINK', 'NP', 'NPR', 'BANK_TRANSFER', 'KRW', '6000', 0.981, TRUE, FALSE, current_timestamp, current_time);

insert into MTO_SERVICE_CENTER(MTO_ID, DISPLAY_ORDER, SERVICE_CENTER_CODE, LOCAL_CODE, DISPLAY_NAME, LOCAL_NAME, DELETED, MODIFIED_TIME, CREATED_TIME)
values ((select ID from MTO where CODE='EASYLINK' and COUNTRY='NP' and CURRENCY='NPR' and REMITTANCE_OPTION='BANK_TRANSFER'),
1, 'ELBT-001', '02011005865', 'Agriculture Development Bank Ltd.', 'Agriculture Development Bank Ltd.', FALSE, current_timestamp, current_timestamp);

insert into MTO_SERVICE_CENTER(MTO_ID, DISPLAY_ORDER, SERVICE_CENTER_CODE, LOCAL_CODE, DISPLAY_NAME, LOCAL_NAME, DELETED, MODIFIED_TIME, CREATED_TIME)
values ((select ID from MTO where CODE='EASYLINK' and COUNTRY='NP' and CURRENCY='NPR' and REMITTANCE_OPTION='BANK_TRANSFER'),
2, 'ELBT-002', '04411001912', 'Annapurna Development Bank', 'Annapurna Development Bank', FALSE, current_timestamp, current_timestamp);

--Nepal EASYLINK Cash pickup
insert into MTO (CODE, COUNTRY, CURRENCY, REMITTANCE_OPTION, FEE_CURRENCY, FEE, EXCHANGE_SPREAD, EXPOSE, DELETED, MODIFIED_TIME, CREATED_TIME)
values ('EASYLINK', 'NP', 'NPR', 'CASH_PICK_UP', 'KRW', '8000', 0.973, TRUE, FALSE, current_timestamp, current_time);

insert into MTO_SERVICE_CENTER(MTO_ID, DISPLAY_ORDER, SERVICE_CENTER_CODE, LOCAL_CODE, DISPLAY_NAME, LOCAL_NAME, DELETED, MODIFIED_TIME, CREATED_TIME)
values ((select ID from MTO where CODE='EASYLINK' and COUNTRY='NP' and CURRENCY='NPR' and REMITTANCE_OPTION='CASH_PICK_UP'),
1, 'ELCP-001', '00000000000', 'EasyLink.', 'EasyLink.', FALSE, current_timestamp, current_timestamp);

insert into MTO_SERVICE_CENTER(MTO_ID, DISPLAY_ORDER, SERVICE_CENTER_CODE, LOCAL_CODE, DISPLAY_NAME, LOCAL_NAME, DELETED, DELETED_TIME, MODIFIED_TIME, CREATED_TIME)
values ((select ID from MTO where CODE='EASYLINK' and COUNTRY='NP' and CURRENCY='NPR' and REMITTANCE_OPTION='CASH_PICK_UP'),
2, 'ELCP-002', '00000000001', 'EasyLink.', 'EasyLink.', true, current_timestamp, current_timestamp, current_timestamp);